-- Store the original 22 foods as the template assigned to every user.
CREATE TABLE public.default_foods (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL UNIQUE
);

INSERT INTO public.default_foods (name)
VALUES
    ('Pizza'),
    ('Pasta'),
    ('Risotto ai funghi'),
    ('Gnocchi'),
    ('Sushi'),
    ('Ramen'),
    ('Udon'),
    ('Soba'),
    ('Poké'),
    ('Falafel'),
    ('Curry'),
    ('Pad thai'),
    ('Cous cous'),
    ('Piadina'),
    ('Focaccia'),
    ('Burger vegetale'),
    ('Tacos'),
    ('Pasta al pesto'),
    ('Pasta al forno'),
    ('Salmone'),
    ('Insalata di riso'),
    ('Lasagne vegetariane');

-- Each user can own multiple food lists.
CREATE TABLE public.food_lists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name text NOT NULL CHECK (btrim(name) <> ''),
    is_default boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- A user can have only one automatically created default list.
CREATE UNIQUE INDEX food_lists_one_default_per_user
    ON public.food_lists (owner_id)
    WHERE is_default;

-- Create a default list for users who already exist.
INSERT INTO public.food_lists (owner_id, name, is_default)
SELECT id, 'I miei cibi', true
FROM auth.users
ON CONFLICT DO NOTHING;

-- Convert foods from global records into records belonging to a list.
ALTER TABLE public.foods
    ADD COLUMN list_id bigint
    REFERENCES public.food_lists(id)
    ON DELETE CASCADE;

-- Remove the old shared copies and recreate an independent copy for each user.
DELETE FROM public.foods;

ALTER TABLE public.foods
    ALTER COLUMN id RESTART WITH 1;

INSERT INTO public.foods (list_id, name)
SELECT food_lists.id, default_foods.name
FROM public.food_lists
CROSS JOIN public.default_foods
ORDER BY food_lists.id, default_foods.id;

ALTER TABLE public.foods
    ALTER COLUMN list_id SET NOT NULL,
    ALTER COLUMN name SET NOT NULL;

CREATE UNIQUE INDEX foods_unique_name_per_list
    ON public.foods (list_id, lower(btrim(name)));

-- Automatically create the default list and its 22 foods for every new user.
CREATE FUNCTION public.create_default_food_list()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
    new_list_id bigint;
BEGIN
    INSERT INTO public.food_lists (owner_id, name, is_default)
    VALUES (NEW.id, 'I miei cibi', true)
    RETURNING id INTO new_list_id;

    INSERT INTO public.foods (list_id, name)
    SELECT new_list_id, name
    FROM public.default_foods
    ORDER BY id;

    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.create_default_food_list() FROM PUBLIC;

CREATE TRIGGER create_food_list_after_signup
AFTER INSERT ON auth.users
FOR EACH ROW
EXECUTE FUNCTION public.create_default_food_list();

-- Remove the old policies that allowed every authenticated user
-- to access the same global foods.
DROP POLICY IF EXISTS "Authenticated users can add foods"
    ON public.foods;

DROP POLICY IF EXISTS "Authenticated users can delete foods"
    ON public.foods;

DROP POLICY IF EXISTS "Authenticated users can read foods"
    ON public.foods;

ALTER TABLE public.default_foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.food_lists ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.foods ENABLE ROW LEVEL SECURITY;

-- Users may read the template but cannot modify it.
CREATE POLICY "Authenticated users can read default foods"
ON public.default_foods
FOR SELECT
TO authenticated
USING (true);

-- Users can access only lists that they own.
CREATE POLICY "Users can read own food lists"
ON public.food_lists
FOR SELECT
TO authenticated
USING (owner_id = auth.uid());

CREATE POLICY "Users can create own food lists"
ON public.food_lists
FOR INSERT
TO authenticated
WITH CHECK (
    owner_id = auth.uid()
    AND is_default = false
);

CREATE POLICY "Users can rename own food lists"
ON public.food_lists
FOR UPDATE
TO authenticated
USING (owner_id = auth.uid())
WITH CHECK (owner_id = auth.uid());

CREATE POLICY "Users can delete own non-default food lists"
ON public.food_lists
FOR DELETE
TO authenticated
USING (
    owner_id = auth.uid()
    AND is_default = false
);

-- Foods are accessible only through a list owned by the user.
CREATE POLICY "Users can read foods in own lists"
ON public.foods
FOR SELECT
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.food_lists
        WHERE food_lists.id = foods.list_id
          AND food_lists.owner_id = auth.uid()
    )
);

CREATE POLICY "Users can add foods to own lists"
ON public.foods
FOR INSERT
TO authenticated
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.food_lists
        WHERE food_lists.id = foods.list_id
          AND food_lists.owner_id = auth.uid()
    )
);

CREATE POLICY "Users can update foods in own lists"
ON public.foods
FOR UPDATE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.food_lists
        WHERE food_lists.id = foods.list_id
          AND food_lists.owner_id = auth.uid()
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM public.food_lists
        WHERE food_lists.id = foods.list_id
          AND food_lists.owner_id = auth.uid()
    )
);

CREATE POLICY "Users can delete foods in own lists"
ON public.foods
FOR DELETE
TO authenticated
USING (
    EXISTS (
        SELECT 1
        FROM public.food_lists
        WHERE food_lists.id = foods.list_id
          AND food_lists.owner_id = auth.uid()
    )
);

-- Restrict anonymous access and grant the authenticated role
-- only the permissions required by the application.
REVOKE ALL ON public.default_foods FROM anon;
REVOKE ALL ON public.food_lists FROM anon;
REVOKE ALL ON public.foods FROM anon;

GRANT SELECT ON public.default_foods TO authenticated;
GRANT SELECT, INSERT, DELETE ON public.food_lists TO authenticated;
GRANT UPDATE (name) ON public.food_lists TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.foods TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

GRANT ALL ON public.default_foods TO service_role;
GRANT ALL ON public.food_lists TO service_role;
GRANT ALL ON public.foods TO service_role;