CREATE TABLE public.foods (
    id bigint GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.food_id_seq) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text,
    CONSTRAINT food_pkey PRIMARY KEY (id)
);