CREATE TABLE public.groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name text NOT NULL CHECK (btrim(name) <> ''),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX groups_unique_name_per_owner
ON public.groups (owner_id, lower(btrim(name)));

CREATE TABLE public.group_members (
    group_id bigint NOT NULL
        REFERENCES public.groups(id)
        ON DELETE CASCADE,
    user_id uuid NOT NULL
        REFERENCES auth.users(id)
        ON DELETE CASCADE,
    role text NOT NULL DEFAULT 'member'
        CHECK (role IN ('owner', 'member')),
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    PRIMARY KEY (group_id, user_id)
);


CREATE FUNCTION public.add_group_owner_as_member()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
    INSERT INTO public.group_members (
        group_id,
        user_id,
        role
    )
    VALUES (
        NEW.id,
        NEW.owner_id,
        'owner'
    );

    RETURN NEW;
END;
$$;

REVOKE ALL
ON FUNCTION public.add_group_owner_as_member()
FROM PUBLIC;


CREATE TRIGGER add_group_owner_after_creation
AFTER INSERT ON public.groups
FOR EACH ROW
EXECUTE FUNCTION public.add_group_owner_as_member();


CREATE FUNCTION public.is_group_member(target_group_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.group_members
        WHERE group_id = target_group_id
          AND user_id = auth.uid()
    );
$$;


CREATE FUNCTION public.is_group_owner(target_group_id bigint)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT EXISTS (
        SELECT 1
        FROM public.groups
        WHERE id = target_group_id
          AND owner_id = auth.uid()
    );
$$;

REVOKE ALL
ON FUNCTION public.is_group_member(bigint)
FROM PUBLIC;

REVOKE ALL
ON FUNCTION public.is_group_owner(bigint)
FROM PUBLIC;

GRANT EXECUTE
ON FUNCTION public.is_group_member(bigint)
TO authenticated;

GRANT EXECUTE
ON FUNCTION public.is_group_owner(bigint)
TO authenticated;


ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.group_members ENABLE ROW LEVEL SECURITY;


CREATE POLICY "Users can read their groups"
ON public.groups
FOR SELECT
TO authenticated
USING (
    owner_id = auth.uid()
    OR public.is_group_member(id)
);


CREATE POLICY "Users can create groups"
ON public.groups
FOR INSERT
TO authenticated
WITH CHECK (
    owner_id = auth.uid()
);


CREATE POLICY "Members can rename groups"
ON public.groups
FOR UPDATE
TO authenticated
USING (
    public.is_group_member(id)
)
WITH CHECK (
    public.is_group_member(id)
);


CREATE POLICY "Owners can delete groups"
ON public.groups
FOR DELETE
TO authenticated
USING (
    owner_id = auth.uid()
);


CREATE POLICY "Members can read group memberships"
ON public.group_members
FOR SELECT
TO authenticated
USING (
    public.is_group_member(group_id)
);


CREATE POLICY "Owners can remove members and members can leave"
ON public.group_members
FOR DELETE
TO authenticated
USING (
    role <> 'owner'
    AND (
        user_id = auth.uid()
        OR public.is_group_owner(group_id)
    )
);


REVOKE ALL ON public.groups FROM anon;
REVOKE ALL ON public.group_members FROM anon;

GRANT SELECT, INSERT, DELETE
ON public.groups
TO authenticated;

GRANT UPDATE (name)
ON public.groups
TO authenticated;

GRANT SELECT, DELETE
ON public.group_members
TO authenticated;

GRANT USAGE, SELECT
ON SEQUENCE public.groups_id_seq
TO authenticated;

GRANT ALL ON public.groups TO service_role;
GRANT ALL ON public.group_members TO service_role;
GRANT ALL ON SEQUENCE public.groups_id_seq TO service_role;